# Generated by Django 2.2.1 on 2019-05-27 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('films_app', '0001_initial'),
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member_watchlist',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_app.Member'),
        ),
        migrations.AddField(
            model_name='film',
            name='actors',
            field=models.ManyToManyField(to='films_app.Actor'),
        ),
        migrations.AddField(
            model_name='film',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_app.Member'),
        ),
    ]
