# Generated by Django 2.2.1 on 2019-05-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films_app', '0002_auto_20190524_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='description',
            field=models.CharField(default=1, max_length=1500),
            preserve_default=False,
        ),
    ]
