# Generated by Django 2.2.1 on 2019-05-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=100)),
                ('movie_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('movie_text', models.CharField(max_length=1500)),
            ],
        ),
    ]
