# Generated by Django 2.2.1 on 2019-05-21 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='member_email',
            field=models.EmailField(default='example@gmail.com', max_length=255, unique=True),
        ),
    ]
